sudo: false

language: scala

dist: xenial

matrix:
  include:
    - env: SBT_VERSION="1.3.3"
      jdk: openjdk11
      scala: 2.12.4

script:
  - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M ++$TRAVIS_SCALA_VERSION "^^${SBT_VERSION}" test scripted